---
name: latest-lts

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Update
        id: update
        uses: docker://garethjevans/jv:0.0.3
        with:
          entrypoint: jv
          args: get --version-identifier lts --github-action-output

      - name: Prepare
        id: prep
        run: |
          FULL_VERSION=${{ steps.update.outputs.jenkins_version }}-jdk11
          echo $FULL_VERSION

