---
name: latest-lts

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Update
        id: update
        uses: docker://garethjevans/jv:0.0.3
        with:
          entrypoint: jv
          args: get --version-identifier lts --github-action-output

      - name: Prepare
        id: prep
        run: |
          FULL_VERSION=jenkins/jenkins:${{ steps.update.outputs.jenkins_version }}-lts-jdk11
          echo $FULL_VERSION
          sed 's|FROM .*|FROM '"${FULL_VERSION}"'|' Dockerfile

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'chore(deps): bump jenkins to ${{ steps.update.outputs.jenkins_version }}'
          committer: Gareth Evans <gareth@bryncynfelin.co.uk>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: 'chore(deps): bump jenkins to ${{ steps.update.outputs.jenkins_version }}'
