---
name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: next release version
        id: nextversion
        uses: jenkins-x-plugins/jx-release-version@v2.4.4
        with:
          next-version: 'semantic:strip-prerelease'

      - name: Prepare
        id: prep
        run: |
          JENKINS_VERSION=$(cat Dockerfile | grep FROM | sed 's|FROM jenkins/jenkins:|-|' | sed 's|-lts-jdk11||')
          DOCKER_IMAGE=garethjevans/jenkins
          VERSION=${{ steps.nextversion.outputs.version }}
          TAGS="${DOCKER_IMAGE}:${VERSION}${JENKINS_VERSION}"
          GIT_TAG="${VERSION}${JENKINS_VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=jenkins-version::${JENKINS_VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Tag
        run: |
          git tag ${{ steps.prep.outputs.version }}${{ steps.prep.outputs.jenkins-version }}
          git push --tags
