---
name: release-drafter
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.22.0
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
