---
name: update

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - run: ./bin/update-plugins.sh
        name: Update plugins

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'chore(deps): update plugins'
          signoff: false
          title: 'chore(deps): update plugins'
          branch: update-plugins
