---
name: update

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Update
        uses: garethjevans/uc@0.0.15

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'chore(deps): update plugins'
          signoff: false
          title: 'chore(deps): update plugins'
          branch: update-plugins
