---
name: update

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Update
        uses: docker://garethjevans/uc:main
        with:
          entrypoint: uc
          args: update --path plugins.txt --jenkins-version 2.263.2 --display-updates-only
